Fix kwargs for Mock calls to delegator
minitest/minitest pull request #935
Opened 2022-11-21 19:08 UTC by blowmage

Propagate keyword arguments when calling Mock's method missing.

Fixes #932.

Since CI is no longer running against Ruby 2.6 the tests won't show fix.
Here is my local reproduction:

```
$ ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin21]
$ rake test
minitest/test_task.rb is now packaged with minitest. If you see
this, you are getting it from hoe instead. If you're NOT able to
upgrade minitest to pick this up, please drop an issue on
seattlerb/hoe and let me know.

Required from /Users/blowmage/.gem/ruby/2.6.6/gems/hoe-3.26.0/lib/hoe/test.rb:86:in `define_test_tasks'
Run options: --seed 41519

# Running:

...................................................................SS.S..SSS....S.....S.....S.....S....................................................................................................................................................................................................................................................................................................................E...........

Finished in 0.247013s, 1696.2670 runs/s, 4991.6401 assertions/s.

  1) Error:
TestMinitestMock#test_delegator_calls_are_propagated:
ArgumentError: wrong number of arguments (given 1, expected 0)
    /Users/blowmage/codez/minitest/test/minitest/test_minitest_mock.rb:268:in `test_delegator_calls_are_propagated'

419 runs, 1233 assertions, 0 failures, 1 errors, 10 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1): [/Users/blowmage/.rubies/ruby-2.6.6/bin/rub...]
/Users/blowmage/.gem/ruby/2.6.6/gems/hoe-3.26.0/lib/minitest/test_task.rb:173:in `block in define'
Tasks: TOP => test
(See full trace by running task with --trace)
$ git checkout fix/mock-delegator-kwargs
M	test/minitest/test_minitest_mock.rb
Switched to branch 'fix/mock-delegator-kwargs'
Your branch is up to date with 'blowmage/fix/mock-delegator-kwargs'.
$ rake test
minitest/test_task.rb is now packaged with minitest. If you see
this, you are getting it from hoe instead. If you're NOT able to
upgrade minitest to pick this up, please drop an issue on
seattlerb/hoe and let me know.

Required from /Users/blowmage/.gem/ruby/2.6.6/gems/hoe-3.26.0/lib/hoe/test.rb:86:in `define_test_tasks'
Run options: --seed 25800

# Running:

.............................................................................................................SS.S..SSS....S.....S.....S.....S......................................................................................................................................................................................................................................................................................

Finished in 0.244547s, 1713.3721 runs/s, 5050.1540 assertions/s.

419 runs, 1235 assertions, 0 failures, 0 errors, 10 skips

You have skipped tests. Run with --verbose for details.
```

2022-12-06 04:01 UTC, zenspider commented
After 87604fca I am starting to wonder if I want about kwargs in mocks entirely incorrectly.

On the one hand, we want to work across all versions of ruby (within reason).

On the other, we'd like to be able to provide quality information when there's a mismatch.

(and on the other, I regret adding mocks to minitest, entirely)

2022-12-06 12:40 UTC, blowmage commented
yuuuuup...

2022-12-17 22:50 UTC, zenspider commented
The test in this PR doesn't fail by itself... either it's incomplete or the problem got fixed in the last merge (doubt it)?

2022-12-17 22:51 UTC, zenspider requested changes
The test in this PR doesn't fail by itself... either it's incomplete or the problem got fixed in the last merge (doubt it)?

2023-01-01 07:46 UTC, zenspider commented
Done. Thanks!

2023-01-01 07:46 UTC, closed without merging